import mongoose from 'mongoose';

const { Schema } = mongoose;

const OrderItemSchema = new Schema({
  productId: {
    type: Schema.Types.ObjectId,
    ref: 'Product',
    required: true,
  },
  productName: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
    min: 0,
  },
  quantity: {
    type: Number,
    required: true,
    min: 1,
  },
  total: {
    type: Number,
    required: true,
    min: 0,
  },
  isSubscription: {
    type: Boolean,
    default: false,
  },
  duration: Number, // For subscription items only
  startDate: Date, // For subscription items only
  endDate: Date, // For subscription items only
}, { _id: false }); // Disable _id for subdocument

const DeliveryAddressSchema = new Schema({
  houseNo: {
    type: String,
    required: true,
  },
  street: {
    type: String,
    required: true,
  },
  area: {
    type: String,
    required: true,
  },
  city: {
    type: String,
    required: true,
  },
  state: {
    type: String,
    required: true,
  },
  pincode: {
    type: String,
    required: true,
    match: /^[0-9]{6}$/,
  },
  landmark: String,
  latitude: Number,
  longitude: Number,
}, { _id: false }); // Disable _id for subdocument

const OrderSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    orderNumber: {
      type: String,
      required: false, // Will be generated by pre-save hook
      unique: true,
      uppercase: true,
    },
    items: {
      type: [OrderItemSchema],
      required: true,
      validate: {
        validator: (items) => items.length > 0,
        message: 'Order must have at least one item',
      },
    },
    subtotal: {
      type: Number,
      required: true,
      min: 0,
    },
    tax: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    deliveryFee: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    oneTimeDeliveryFee: {
      type: Number,
      min: 0,
      default: 0,
    },
    subscriptionDeliveryFee: {
      type: Number,
      min: 0,
      default: 0,
    },
    discount: {
      type: Number,
      min: 0,
      default: 0,
    },
    totalAmount: {
      type: Number,
      required: true,
      min: 0,
    },
    deliveryAddress: {
      type: DeliveryAddressSchema,
      required: false,
    },
    oneTimeDeliveryAddress: {
      type: DeliveryAddressSchema,
      required: false,
    },
    subscriptionDeliveryAddress: {
      type: DeliveryAddressSchema,
      required: false,
    },
    useSameAddress: {
      type: Boolean,
      default: true,
    },
    deliveryType: {
      type: String,
      enum: ['express', 'scheduled', 'standard'],
      default: 'standard',
    },
    deliveryDistance: {
      type: Number,
      min: 0,
      default: 0,
    },
    deliverySlot: {
      type: String,
      required: true,
    },
    deliveryDate: {
      type: Date,
      required: true,
    },
    status: {
      type: String,
      enum: ['pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled'],
      default: 'pending',
      index: true,
    },
    paymentMethod: {
      type: String,
      enum: ['cod', 'online', 'wallet'],
      required: true,
    },
    paymentStatus: {
      type: String,
      enum: ['pending', 'paid', 'failed', 'refunded'],
      default: 'pending',
      index: true,
    },
    paymentId: String,
    couponCode: String,
    specialInstructions: {
      type: String,
      maxlength: 500,
    },
    cancelReason: String,
    cancelledAt: Date,
    confirmedAt: Date,
    preparedAt: Date,
    outForDeliveryAt: Date,
    deliveredAt: Date,
  },
  {
    timestamps: true,
  }
);

// Generate order number before saving
OrderSchema.pre('save', async function (next) {
  if (this.isNew) {
    const count = await mongoose.model('Order').countDocuments();
    const timestamp = Date.now().toString().slice(-6);
    this.orderNumber = `ORD${timestamp}${(count + 1).toString().padStart(4, '0')}`;
  }
  next();
});

// Comprehensive indexes for high-performance order queries (1L+ users)
// User-specific queries (most common)
OrderSchema.index({ userId: 1, createdAt: -1 }); // User's orders by date
OrderSchema.index({ userId: 1, status: 1 }); // User's orders by status
OrderSchema.index({ userId: 1, status: 1, createdAt: -1 }); // User's orders by status + date

// Admin/operational queries
OrderSchema.index({ status: 1, deliveryDate: 1 }); // Orders by status + delivery date
OrderSchema.index({ status: 1, createdAt: -1 }); // Orders by status + creation date
OrderSchema.index({ deliveryDate: 1, status: 1 }); // Delivery schedule + status
OrderSchema.index({ createdAt: -1 }); // Recent orders first

// Payment-related queries
OrderSchema.index({ paymentStatus: 1, createdAt: -1 }); // Payment tracking
OrderSchema.index({ paymentMethod: 1, paymentStatus: 1 }); // Payment method analysis

// Delivery tracking
OrderSchema.index({ 'deliveryAddress.pincode': 1, deliveryDate: 1 }); // Area-based delivery (legacy)
OrderSchema.index({ 'oneTimeDeliveryAddress.pincode': 1, deliveryDate: 1 }); // One-time delivery area
OrderSchema.index({ 'subscriptionDeliveryAddress.pincode': 1, deliveryDate: 1 }); // Subscription delivery area
OrderSchema.index({ deliveryDate: 1, deliverySlot: 1 }); // Delivery scheduling
OrderSchema.index({ deliveryType: 1, status: 1 }); // Delivery type analysis

// Analytics and reporting
OrderSchema.index({ createdAt: 1, status: 1 }); // Time-series status analysis
OrderSchema.index({ totalAmount: 1 }); // Revenue queries

// Geospatial index for location-based queries (if lat/lng available)
OrderSchema.index({ 'deliveryAddress.latitude': 1, 'deliveryAddress.longitude': 1 });

export default mongoose.model('Order', OrderSchema);
